= Protection Profile for General Purpose Operating Systems

[cols="1,1,1,1,1,1"]
|===
| Master
a|[link=https://github.com/commoncriteria/operatingsystem/blob/gh-pages/master/ValidationReport.txt] 
image::https://raw.githubusercontent.com/commoncriteria/operatingsystem/gh-pages/master/validation.svg[validation]
a|[link=https://github.com/commoncriteria/operatingsystem/blob/gh-pages/master/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/operatingsystem/gh-pages/master/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/operatingsystem/blob/gh-pages/master/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/operatingsystem/gh-pages/master/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/operatingsystem/blob/gh-pages/master/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/operatingsystem/gh-pages/master/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/operatingsystem/gh-pages/master/transforms.svg[transforms,150]
| release-4.3
a|[link=https://github.com/commoncriteria/operatingsystem/blob/gh-pages/release-4.3/ValidationReport.txt] 
image::https://raw.githubusercontent.com/commoncriteria/operatingsystem/gh-pages/release-4.3/validation.svg[validation]
a|[link=https://github.com/commoncriteria/operatingsystem/blob/gh-pages/release-4.3/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/operatingsystem/gh-pages/release-4.3/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/operatingsystem/blob/gh-pages/release-4.3/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/operatingsystem/gh-pages/release-4.3/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/operatingsystem/blob/gh-pages/release-4.3/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/operatingsystem/gh-pages/release-4.3/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/operatingsystem/gh-pages/release-4.3/transforms.svg[transforms,150]
| release-4.2.1
a|[link=https://github.com/commoncriteria/operatingsystem/blob/gh-pages/release-4.2.1/ValidationReport.txt] 
image::https://raw.githubusercontent.com/commoncriteria/operatingsystem/gh-pages/release-4.2.1/validation.svg[validation]
a|[link=https://github.com/commoncriteria/operatingsystem/blob/gh-pages/release-4.2.1/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/operatingsystem/gh-pages/release-4.2.1/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/operatingsystem/blob/gh-pages/release-4.2.1/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/operatingsystem/gh-pages/release-4.2.1/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/operatingsystem/blob/gh-pages/release-4.2.1/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/operatingsystem/gh-pages/release-4.2.1/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/operatingsystem/gh-pages/release-4.2.1/transforms.svg[transforms,150]
|===

[link=https://github.com/commoncriteria/operatingsystem/issues]
image::https://img.shields.io/github/issues/commoncriteria/operatingsystem.svg[GitHub issues Open]


This repository hosts the draft version of the Protection Profile for a General Purpose Operating System based on the 
https://commoncriteria.github.io/pp/operatingsystem/operatingsystem-esr.html[Essential Security Requirements (ESR)] for this technology class of 
products. This repository is used to facilitate collaboration and development on the draft document. 
See the xref:readme#Release-Version[release] section if you are looking for the officially released version for evaluations. 
A list of products that have passed evaluation against this Protection Profile can be found https://www.niap-ccevs.org/Profile/Info.cfm?id=400[here].

== Draft Version

* https://commoncriteria.github.io/pp/operatingsystem/operatingsystem-release.html[Protection Profile for General Purpose Operating System] (html)
* https://commoncriteria.github.io/pp/operatingsystem/operatingsystem-release.pdf[Protection Profile for General Purpose Operating System] (pdf)
* https://commoncriteria.github.io/pp/operatingsystem/configannex.html[Configuration Annex to the General Purpose Operating System] (html)
* https://commoncriteria.github.io/operatingsystem/diff-release-4.2.1.html[Diff against v4.2.1] (html)
* https://commoncriteria.github.io/operatingsystem/diff-v4.3-comment-1.html[Diff against v4.3-draft-1] (html)


== Release Version

* https://www.niap-ccevs.org/Profile/Info.cfm?PPID=442&id=442[Protection Profile for General Purpose Operating System v4.2.1]

== Contributing

If you are interested in contributing directly to future versions the this Protection Profile, please consider joining the NIAP technical community.
* https://www.niap-ccevs.org/NIAP_Evolution/tech_communities.cfm[How to join the NIAP Technical Community (Mailing list and updates)]

== Feedback

Questions, comments, and fixes can be submitted to the https://github.com/commoncriteria/operatingsystem/issues[repository issue tracker]

== Quickstart
To clone this project along with its _transforms_ submodule run:

````
  git clone --recursive git@github.com:commoncriteria/operatingsystem.git
````
To pull updates from the upstream _transforms_ submodule and commit them run:
````
 git submodule update --remote transforms
 git add transforms
 git commit
````


=== Development Info
* https://github.com/commoncriteria/transforms/wiki/Working-with-Transforms-as-a-Submodule[Help working with Transforms Submodule]
* https://github.com/commoncriteria/pp-template/wiki[Protection Profile Development Getting Started Guide]


== Repository Content
* input - Contains the 'meat' of the project. It's the input content (in XML form) that gets transformed to readable html.
* output - The output directory where the html is placed after transformation.
* output/images - The directory where images are stored
* transforms - Points to the transform subproject which is really a repository for resources shared amongst many Common Criteria projects.


== Links 
* https://www.niap-ccevs.org/[National Information Assurance Partnership (NIAP)]
* https://www.commoncriteriaportal.org/[Common Criteria Portal]


== License

See [License](./LICENSE)

